### ISSUE TITLE
Need to transform -*Version parameters to -Version for all cmdlets that support NuGet version strings

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShellGet#27]
### Summary of the new feature / enhancement

The following cmdlets in **Microsoft.PowerShell.PSResourceGet** have a **Version** parameter that takes a Nuget version range.

- Find-PSResource
- Get-InstalledPSResource
- Install-PSResource
- Save-PSResource
- Uninstall-PSResource
- Update-PSResource

The following proxy cmdlet need to have code to transform the _\*Version_ parameters to a NuGet version string.

- Find-Command
- Find-DscResource

**Comment by alerickson** [comment]
Closing this issue because both `Find-PSResource -CommandName`  and  `Find-PSResource -DscResourceName` do not allow `-Version`.  This is because it's an extremely costly operation server side.
