### ISSUE TITLE
Find-module/find-script does not find any modules/scripts hosted on a private nuget feed.

### ISSUE THREAD

**Issue by whiggs** [PowerShell/PowerShellGet#384]
I have an environment where we have a [self-hosted nuget server instance](https://github.com/NuGet/NuGet.Server) that has been set up to have [multiple nuget feeds](https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server).  One of these nuget feeds is going to be used to host powershell modules and scripts.  I have installed the latest packagemanagement and powershellget powershell modules, and registered the nuget feed in question with register-psrepository.  I then attempted to publish a test module to this newly registered nuget feed.  The command did not return an error, so, in an attempt to verify that the module was pushed, I ran a "find-module" command to return a modules hosted on the registered repository.  However, find-module did not return any hosted modules.  After some testing, I found that the powershell module had actually been published to the nuget feed, as I could save and install the module from the repository and the module was listed in the nuget server's package directory.  Therefore, I can only conclude that find-module does not work when querying a repository hosted on a self-hosted nuget server.  [Here](https://showmore.com/u/34pn9ub) is a video displaying the issue.

**UPDATE:**  The same behavior is occurring with scripts as well.

Steps to reproduce
------------------
For a nuget feed setup as indicated above and register one of the nuget feeds:
```powershell
Register-PSRepository -Name Test2 -SourceLocation "http://localhost:8180/nugetfeed" -PublishLocation "http://localhost:8180/nugetfeed" -PackageManagementProvider nuget -InstallationPolicy Trusted
Publish-Module -Path "C:\path\to\module" -NuGetApiKey "<nugetapikey>" -Repository "Test2" -Force -Confirm:$false
Find-Module -Filter * -Repository "Test2"  #This returns nothing
save-module -Name "<modulename>" -Repository "Test2" -Path C:\temp -Force -Confirm:$false  #But this will download the module successfully.
```

Expected behavior
-----------------
Find-module should return the module I just published to the private nuget feed
```none

```

Actual behavior
---------------
Find-module returns nothing.
```none

```

Environment data
----------------

```powershell
$PSVersionTable

Name                           Value                                                                                                               
----                           -----                                                                                                               
PSVersion                      5.1.14409.1018                                                                                                      
PSEdition                      Desktop                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                             
BuildVersion                   10.0.14409.1018                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                     
WSManStackVersion              3.0                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                 
SerializationVersion           1.1.0.1          

```

```powershell
> Get-Module -ListAvailable PowerShellGet,PackageManagement


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                         
---------- -------    ----                                ----------------                                                                         
Script     1.2.4      PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                   
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                   
Script     2.0.3      PowerShellGet                       {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability...}                    
Script     1.5.0.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}                             
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}    

```

```powershell
> Get-PackageProvider -ListAvailable

Name                     Version          DynamicOptions                                                                                           
----                     -------          --------------                                                                                           
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion, ForceX86, PackageSaveMode, FilterOnTag, Contains,...
msi                      3.0.0.0          AdditionalArguments                                                                                      
msu                      3.0.0.0                                                                                                                   
nuget                    2.8.5.208                                                                                                                 
NuGet                    3.0.0.1          Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseV...
PowerShellGet            2.0.3.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate,...
PowerShellGet            1.5.0.0                                                                                                                   
PowerShellGet            1.0.0.1                                                                                                                   
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent                                                          


```

**Comment by alerickson** [comment]
Thanks for reporting this bug!  I do find odd that install is working since it calls find.  If find isn't actually finding the modules, it shouldn't be able to install them.

**Comment by whiggs** [comment]
@alerickson Yeah, I find that odd too.  At first, even after I had updated to the latest version of Powershellget, removed the old version, and specifically imported the new version, I kept getting the below error until I launched a new powershell session:
![image](https://user-images.githubusercontent.com/11139575/50121739-ad8a1a80-0227-11e9-8fbb-10b1ec6dad4c.png)
And, to make sure that the powershell session is using the latest version of powershellget, I always run the below snippet at the beginning of each new powershell session

```poweshell
Remove-Module powershellget -Force -Confirm:$false
Remove-Module PackageManagement -Force -Confirm:$false
Import-module powershellget -Force -RequiredVersion 2.0.3
```

This is a complete shot in the dark, but I due have a couple of theories:
1.  The functionality which allows for multiple nuget feeds for a single [Nuget.Server](https://github.com/NuGet/NuGet.Server) instance was recently released (from what I understand), so maybe it is this feature which has broken it.
2. The web.config file, specifically the section which defines the nuget feeds and api keys, is encrypted, so maybe that might be what is causing it:
![image](https://user-images.githubusercontent.com/11139575/50122304-d0b5c980-0229-11e9-8e0f-a545bc08cdaf.png)

But like I said, complete shots in the dark.  Hopefully this helps you all figure it out.

**Comment by edyoung** [comment]
Private nuget feeds do work in most cases, there is likely something more
specific going on. Some suggestions to narrow down the problem:

Try:

Find-Module -Repository Test2 # without the -Filter
Find-Module <modulename> -Repository Test2 # specify module explicitly

**Comment by whiggs** [comment]
@edyoung Very interesting suggesstions.  Both of your suggestions returned results, but only the command where I specifically define the module name worked 100% as expected.  What I mean by that is that, when I run "Find-module -repository test2", it does return the modules which I published, but it also returns items which are NOT modules (eg. published scripts).  
![image](https://user-images.githubusercontent.com/11139575/50224053-e252ba80-036a-11e9-9ab7-74d8d1bc6d91.png)

**Comment by alerickson** [comment]
That's interesting... running find-package with -name did not return the package I was looking for, but without -name did.

**Comment by whiggs** [comment]
????

![image](https://user-images.githubusercontent.com/11139575/50235863-e8569480-0386-11e9-847f-2a6b6c0d50f5.png)

**Comment by alerickson** [comment]
@whiggs just out of curiosity could you try that with find-package?

**Comment by whiggs** [comment]
Same parameters?

**Comment by whiggs** [comment]
interesting.  Same results.

![image](https://user-images.githubusercontent.com/11139575/50236193-c9a4cd80-0387-11e9-92d5-bce15a074137.png)

**Comment by alerickson** [comment]
That's really helpful.  Still surprised I had different results, but it's good to know it's at least consistent with find-module.

**Comment by whiggs** [comment]
Glad it helped.  Let me know if you need anything else from me.

**Comment by edyoung** [comment]
Nuget doesn't natively understand the difference between Modules and Scripts. PowerShellGet handles that by allowing you to have 2 separate feeds, one for scripts and one for modules. You can specify these when you register the repository with -SourceLocation/PublishLocation (modules) and -ScriptSourceLocation/ScriptPublishLocation (scripts). That's why you are seeing scripts and modules intermixed. If you don't care, ignore it; if you care, use those params to specify a separate feed for scripts.
 
Regarding why -Filter * doesn't work, it may be an incompatibility between how your local nuget feed interprets the nuget API and how PowerShellGet does. What is the Nuget feed (VSTS, ProGet, etc?)

**Comment by whiggs** [comment]
@edyoung Please see the very first link in the very first post.  The one that reads "self-hosted nuget server instance"
