### ISSUE TITLE
Check `-Scope` parameter for all cmdlets

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/PowerShellGet#595]
### Summary of the new feature / enhancement

Be sure, where it makes sense, that the -Scope parameter is included in cmdlets. Ensure it works as expected if implemented. Related issues:
#309

**Comment by weyCC81** [comment]
I would also like that parameter! https://github.com/PowerShell/PowerShell/issues/16729

**Comment by SydneyhSmith** [comment]
Closing in favor of #616 and #309

**Comment by schittli** [comment]
Yet another Microsoft disgrace: they make so many billions from us customers that it's hard to count, but such simple and obvious feature requests are ignored for years.
