### ISSUE TITLE
Cannot create account at poshtestgallery.com

### ISSUE THREAD

**Issue by rinrab** [PowerShell/PowerShellGet#71]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

I cannot create an account at poshtestgallery.com.

### Steps to reproduce

Create account at poshtestgallery.com with email or username which are already exists at powershellgallerry.com

### Expected behavior

I could login to my account from the real powershellgallerry or create a new at poshtestgallery.

### Actual behavior

Throws error when I try to login to my Microsoft account.

### Error details

```
Oops!

Error 500 - Internal Server Error

An error occurred while processing your request. We really messed up this time...

We have logged the error and will look into it so that it doesn't happen again; however, if you keep seeing this page, please file a bug!

Get me out of here! Go home

Wondering if PowerShell Gallery is down? Check our status

Looking for a package? Try searching

Package you're looking for doesn't exist? Make one

Pretty sure we messed up? File a bug
```

**Comment by SydneyhSmith** [comment]
@rinrab poshtestgallery is not a public repository, it is just a test environment for PsGallery updates-- only used by our team

**Comment by rinrab** [comment]
Ou, sorry. I thought that this is a powershell gallery to test my module before publish.

Additionally, I think it would be great to have the same gallery for example for testing publish scripts and having nighty-built modules.
